### ISSUE TITLE
Replace DwtHtmlEditor by ZmHtmlEditor for compatibility from zimbra > 8.6.0

### ISSUE THREAD

**Issue by mistraloz** [barrydegraaff/pgp-zimlet#82] opened 2015-04-28 09:00 UTC
DwtHtmlEditor is no more. ZmHtmlEditor repmlace them.

**Comment by barrydegraaff** [comment] 2015-04-28 10:29
If you have more details, then those details are very welcome.

As there is currently no public beta for ZCS > 8.6 available and the source from git cannot be build.

Some stuff that we use:
                 var composeController = AjxDispatcher.run("GetComposeController");
                 if(composeController) {
                    var appCtxt = window.top.appCtxt;
                    var zmApp = appCtxt.getApp();
                    var newWindow = zmApp != null ? (zmApp._inNewWindow ? true : false) : true;
                    var params = {action:ZmOperation.NEW_MESSAGE, inNewWindow:null, composeMode:Dwt.TEXT,
                    toOverride:null, subjOverride:null, extraBodyText:signed, callback:null}
                    composeController.doAction(params); // opens asynchronously the window.


And:
   var composeMode = appCtxt.getCurrentView().getHtmlEditor().getMode();
   var message = controller._getBodyContent();
  
   if(composeMode != 'text/plain')
   {
      var composeView = appCtxt.getCurrentView();   
      composeView.getHtmlEditor().setContent('');    

      controller._setFormat(Dwt.TEXT);
      composeView.getHtmlEditor().setMode(Dwt.TEXT);   
      composeView.getHtmlEditor().setContent(message);

**Comment by weSh** [comment] 2015-05-16 05:04
it seems that we still have the error:
Impossible d'initialiser le zimlet "tk_barrydegraaff_zimbra_openpgp". Contactez l'administrateur.
ReferenceError: DwtHtmlEditor is not defined

**Comment by barrydegraaff** [comment] 2015-05-16 06:14
I do not have this problem when using:
Release 8.6.0_GA_1153.RHEL7_64_20141215151110 RHEL7_64 FOSS edition, Patch 8.6.0_P2.
And the git version of the Zimlet.

So I assume it is in ZCS 8.7 or 9. What version of Zimbra are you using? Please provide output of zmcontrol -v and also install the latest version of the zimlet.

Also I do NOT use DwtHtmlEditor, maybe it is a dependency of another dwt component, but as there is no public beta of 8.7 nor can Zimbra be build from source right now, I cannot reproduce this problem to fix it.

**Comment by weSh** [comment] 2015-05-16 06:20
Hi,

thanks for your reply.
Here is my version: Release 8.6.0.GA.1153.UBUNTU14.64 UBUNTU14_64 FOSS edition

I use the zimlet downloaded here: https://gallery.zimbra.com/type/zimlet/zimbra-openpgp-zimlet

Is it ok?

**Comment by barrydegraaff** [comment] 2015-05-16 06:35
Yes, it should work, not trowing that error, can you provide me with a test account?
You can send the login details to info@barrydegraaff.tk you may wish to encrypt using:
http://keyserver.ubuntu.com/pks/lookup?op=get&fingerprint=on&search=0x725DDD156D36A2D0

I just installed the zip file from the gallery on 
Release 8.6.0_GA_1153.RHEL7_64_20141215151110 RHEL7_64 FOSS edition, Patch 8.6.0_P2.

There was no error.

Thanks

**Comment by weSh** [comment] 2015-05-16 07:24
Yep,

I found the solution: it's mandatory to have Patch 8.6.0_P2 installed.
Now, it works!
Thanks for your time and your help!

**Comment by barrydegraaff** [comment] 2015-05-16 07:29
I am happy it works now, but I suspect it was something else since there is no reason for the Zimlet initialization (.init) to do something with DwtHtmlEditor.

**Comment by barrydegraaff** [comment] 2015-05-16 08:24
Also the version currently on gallery is a bit rough around the edges, since we started integrating in to the message view this week.

You can try to install the dev version using git clone, ./install-dev.sh , first undeploy the zip version.

Or wait and try the next version that I'd released soon. That will look a lot better.

Barry

--- Original Message ---

**Comment by weSh** [comment] 2015-05-16 08:38
Thanks for this.
I think it would be wiser to wait the stable release... ;-)
Server is in production and I prefer to be sure that everything is stable.

Congrats for your job! Really impressive!

**Comment by barrydegraaff** [comment] 2015-08-18 08:11
pgp zimlet is tested to be compatible with 
Zimbra 8.7.0_BETA1_1294 (build 20150801180818)

So we can close this.

**Closed by barrydegraaff** 2015-08-18 08:11 UTC
